[build]
publish = "."
functions = "netlify/functions"

[dev]
publish = "."
port = 8888

[[redirects]]
from = "/Dashboard"
to = "/Dashboard/index.html"
status = 200

[[redirects]]
from = "/Dashboard/"
to = "/Dashboard/index.html"
status = 200

[[redirects]]
from = "/lyricshot"
to = "/lyricshot.html"
status = 200

[[redirects]]
from = "/workspace"
to = "/workspace.html"
status = 200
